name: aedove
description: "A simple cross-platform file sharing app."
publish_to: 'none'
version: 1.0.0+3

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  http: ^1.1.0
  file_picker: ^8.0.0+1
  permission_handler: ^11.0.1
  path_provider: ^2.1.1
  mime: ^1.0.4
  uuid: ^4.1.0
  multicast_dns: ^0.3.2
  filesize: ^2.0.1
  # flutter_local_notifications: ^19.5.0
  shared_preferences: ^2.5.2
  connectivity_plus: ^6.1.0
  network_info_plus: ^6.1.1
  device_info_plus: ^11.1.1
  intl: ^0.20.2
  image: ^4.5.4
  image_picker: ^1.1.2
  gal: ^2.3.0
  # For automated WiFi file sharing
  crypto: ^3.0.6
  # For network discovery and file sharing
  socket_io_client: ^2.0.3+1
  bonsoir: ^6.0.1
  path: ^1.8.3
  awesome_notifications: ^0.10.1
  flutter_inappwebview: ^6.1.5


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.4.0

flutter:
  uses-material-design: true

  assets:
     - assets/images/

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  remove_alpha_ios: true
  image_path: "assets/images/aedove-logo.png"
  web:
    generate: true
    image_path: "assets/images/aedove-logo.png"
    background_color: "#ffffff"
    theme_color: "#0175C2"
  macos:
    generate: true
    image_path: "assets/images/aedove-logo.png"
  windows:
    generate: true
    image_path: "assets/images/aedove-logo.png"
    icon_size: 256

flutter_native_splash:
  color: "#ffffff"
  image: assets/images/aedove-logo-trans.png
  color_dark: "#000000"
  image_dark: assets/images/aedove-logo-trans.png
  
  android_12:
    color: "#ffffff"
    image: assets/images/aedove-logo-trans.png
    icon_background_color: "#ffffff"
    color_dark: "#000000"
    image_dark: assets/images/aedove-logo-trans.png
    icon_background_color_dark: "#000000"
  
  web: true
  ios: true
  android: true